# -*- coding: utf-8 -*-
"""pandas.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AtPFyltr2MveDfFL-czMqeA6gkwl9TdE
"""

import pandas as pd
pd.DataFrame({"Apple":[30],"Bananas":[21]})



import pandas as pd
pd.DataFrame({"Apple":[35,41],"Bananas":[21,34]},index=["2017 Sales","2018 Sales"])

ingredients = pd.Series(['4 cups','1 cup','2 large','1 can'],index=['flour','Milk','Eggs','spam'],name='Dinner')
print(ingredients)

# Commented out IPython magic to ensure Python compatibility.
import os

# your GitHub details
os.environ['GITHUB_USER'] = "sanjanasowmya-wq"
os.environ['GITHUB_TOKEN'] = "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"

# clone your private repo
!git clone https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$GITHUB_USER/llm-colab-demo.git

# move inside repo
# %cd llm-colab-demo

# list files
!ls